### ISSUE TITLE
Attach marker to converted structure, to avoid double scans

### ISSUE THREAD

**Issue by axgkl** [axiros/nested_encode#1]
Hi Stephan,

since it'll take a while until we have the nested_encode in all our core code (like AXSS):

Users will have to run the function in project code or Extensions like v1.
So we will have then double scans if we later add it to the core.

=> Possible to avoid double scanning by a flag in the converted object, which you check before scanning?

**Comment by stephan-hof** [comment]
Yes I could think of a marker, however I'm not sure how to implement this. All the builtin python types do not allow assignment. For example all of the following calls fail with an AttributeError:

``` python
x = {}
setattr(x, 'tag', True)

x = []
setattr(x, 'tag', True)

x = True
setattr(x, 'tag', True)

x = 'test'
setattr(x, 'tag', True)
```

**Comment by axgkl** [comment]
"only" needed for lists and dicts, i.e. where scanning recursively could get expensive.
I know that in Python list and dict are completely static - and wrapping them into a custom class (like we did with OrderedDict in 2.6) would be too expensive. Thought though that maybe in C there might be lower lever possibilities to have write access to a property of the generated structure, which you could check the second time, when asked to convert it.

**Comment by stephan-hof** [comment]
Sorry, at the C-Level the '_dictobject' has no extra space where such a tag could be stored :(
These two objects (dict, list) are heavily optimized, which makes it very unlikely that they have a 'free slot'. For example the dict object has the following fields
- refcount
- pointer to the 'class' definition
- 6 attributes dedicated for the hashtable

**Comment by axgkl** [comment]
offering a way to patch json's loads then in our toolchain - then we don't even need to bother about double scans.
